/*Ejemplos de particionado por RANGE y COMBINE(RANGE - HASH)*/
/*Página de referencia: https://churriwifi.wordpress.com/2010/04/24/15-2-1-particionado-en-oracle/#:~:text=Basicamente%2C%20el%20particionado%20se%20realiza,de%20tablas%20organizadas%20por%20indices.*/

drop table sales;
CREATE TABLE sales
( prod_id NUMBER(6)
, cust_id NUMBER
, time_id DATE
, channel_id CHAR(1)
, promo_id NUMBER(6)
, quantity_sold NUMBER(3)
, amount_sold NUMBER(10,2)
)
PARTITION BY RANGE (time_id)
( PARTITION sales_q1_2006 VALUES LESS THAN (TO_DATE('2006/04/01 8:30:25', 'YYYY/MM/DD HH:MI:SS')) TABLESPACE system
, PARTITION sales_q2_2006 VALUES LESS THAN (TO_DATE('2006/06/01 8:30:25', 'YYYY/MM/DD HH:MI:SS')) TABLESPACE system
, PARTITION sales_q3_2006 VALUES LESS THAN (TO_DATE('2006/08/01 8:30:25', 'YYYY/MM/DD HH:MI:SS')) TABLESPACE system
, PARTITION sales_q4_2006 VALUES LESS THAN (TO_DATE('2007/01/01 8:30:25', 'YYYY/MM/DD HH:MI:SS')) TABLESPACE system
);

drop table TAB2;
CREATE TABLE TAB2 (ord_id     NUMBER(10), ord_day    NUMBER(2), ord_month  NUMBER(2),  ord_year   NUMBER(4) )
PARTITION BY RANGE(ord_year)
SUBPARTITION BY HASH(ord_id)
SUBPARTITIONS 8
( PARTITION q1 VALUES LESS THAN(2001)
( SUBPARTITION q1_h1 TABLESPACE SYSTEM, SUBPARTITION q1_h2 TABLESPACE SYSTEM,
SUBPARTITION q1_h3 TABLESPACE SYSTEM,SUBPARTITION q1_h4 TABLESPACE SYSTEM ),
PARTITION q2 VALUES LESS THAN(2002)
( SUBPARTITION q2_h5 TABLESPACE SYSTEM,SUBPARTITION q2_h6 TABLESPACE SYSTEM,
SUBPARTITION q2_h7 TABLESPACE SYSTEM,SUBPARTITION q2_h8 TABLESPACE SYSTEM),
PARTITION q3 VALUES LESS THAN(2003)
( SUBPARTITION q3_h1 TABLESPACE SYSTEM,SUBPARTITION q3_h2 TABLESPACE SYSTEM,
SUBPARTITION q3_h3 TABLESPACE SYSTEM,SUBPARTITION q3_h4 TABLESPACE SYSTEM),
PARTITION q4 VALUES LESS THAN(2004)
( SUBPARTITION q4_h5 TABLESPACE SYSTEM,SUBPARTITION q4_h6 TABLESPACE SYSTEM,
SUBPARTITION q4_h7 TABLESPACE SYSTEM,SUBPARTITION q4_h8 TABLESPACE SYSTEM) );


select * from tab2;